language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r-packages:
- colorspace
- RColorBrewer
- testthat
- knitr
- markdown
- dendextend
- GlobalOptions
- circlize
- GetoptLong
- covr

bioc_packages:
- GenomicRanges
- HilbertVis
- HilbertCurve

r_check_args: --no-build-vignettes --no-vignettes

after_success:
  - Rscript -e 'library(covr);codecov()'
  
